# Spring properties
spring:
  application:
    name: users-service  # Service registers under this name
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3355/demo
    username: root
    password: bfhs7Hi38o1Bas8jH90VS
     
# JWT
security:
  jwt:
    secret-key: 0f08458d217e4eccbc506997e24ffe5e039072c4fc76fe52f94278337795e8af
    expiration-time: 3600000

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port